version: "3.9"

networks:
  demo:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - demo
