apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: demo-org
      defaultBucket: demo-bucket
      tlsSkipVerify: true
    secureJsonData:
      token: demo-token
    isDefault: true
