networks:
  demo:
    driver: bridge

services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: a123456789
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - demo
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "demo", "-U", "demouser"]
      interval: 15s
      timeout: 30s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:0.16.2
    container_name: pgweb
    restart: always
    ports:
      - 8081:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://demouser:a123456789@postgres:5432/demo?sslmode=disable
    networks:
      - demo
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
