networks:
  demo:
    driver: bridge

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: a123456789
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "demo", "-U", "demouser"]
      interval: 15s
      timeout: 30s
      retries: 5
    networks:
      - demo

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: a123456789
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - demo
    depends_on:
      postgres:
        condition: service_healthy
