services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: Keycloak
    command: start-dev --import-realm
    restart: always
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./realms.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/9000 && echo OK || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 20s
