networks:
  demo:
    driver: bridge

services:
  oteltui:
    image: ymtdzzz/otel-tui:v0.5.2
    container_name: otel-tui
    stdin_open: true
    tty: true
    ports:
      - 4317:4317
      - 4318:4318
    networks:
      - demo

  telemetrygen:
    image: golang:1.24.5
    container_name: telemetrygen
    stdin_open: true
    tty: true
    working_dir: /go
    command: >
      bash -c "
      go install github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen@latest &&
      exec /bin/bash"
    networks:
      - demo
