networks:
  demo:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - demo

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - demo
    depends_on:
      - zookeeper
    command:
      - bash
      - -c
      - >-
        (sleep 10 &&
        echo "########################## CREATING TOPICS... ##########################" &&
        /usr/bin/kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic demo.topic.boo &&
        /usr/bin/kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic demo.topic.foo &&
        echo "########################## TOPICS CREATED. ##########################" ) &
        /etc/confluent/docker/run

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - demo
    depends_on:
      - kafka
