services:
  macos:
    image: dockurr/macos:2.13
    container_name: macos
    environment:
      VERSION: "15"
      RAM_SIZE: "2G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
