networks:
  demo:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672 # WebUi
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - demo
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 3s
      retries: 5
