@host = http://localhost:5000

### Health check - Ready

GET {{host}}/_mockaco/ready

### Health check - health

GET {{host}}/_mockaco/health

### Demos

GET {{host}}/comments

###

GET {{host}}/comments?postId=121
