networks:
  demo:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      MSSQL_PID: Developer
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Ab123456!
    ports:
      - 1433:1433
    networks:
      - demo
    healthcheck:
      test: >
        /bin/bash -c "echo > /dev/tcp/localhost/1433"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssqltools
    volumes:
      - ./init-db.sql:/tmp/init-db.sql
      - ./init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh
    networks:
      - demo
    depends_on:
      sqlserver:
        condition: service_healthy
