server:
  http_listen_port: 9080
  grpc_listen_port: 9081

positions:
  filename: /mnt/config/positions.yaml
  sync_period: 10s

clients:
  - url: http://loki:3100/loki/api/v1/push


scrape_configs:

  - job_name: 'DemoJob'
    static_configs:
      - labels:
          serviceType: 'DemoServer'
          serviceName: 'DemoName'
          __path__: /var/demo-logs/*log
