networks:
  demo:
    driver: bridge

services:
  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:1.1.2
    container_name: servicebus-emulator
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: Ab123456789!
      ACCEPT_EULA: Y
      SQL_WAIT_INTERVAL: 1
    volumes:
      - ./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - 5672:5672
    networks:
      - demo
    depends_on:
      sqledge:
        condition: service_healthy # waits for db healthcheck to be successful

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:2.0.0
    container_name: sqledge
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Ab123456789!
    networks:
      - demo
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -C -U sa -Q "SELECT 1"
      interval: 5s
      timeout: 3s
      retries: 5
