global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'Prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          serviceType: 'Observability'
          serviceName: 'Prometheus.Service'
