@host = http://localhost:8080


###

POST {{host}}/api/users
Accept: application/json

{
    "id": "44238234-7df5-470e-a110-7c4b42c2e4a5",
    "name": "john Doe",
    "email": "john.doe@fake.com"
}


### ADMIN

### Health Check
GET {{host}}/__admin/health

#### Mappings
GET {{host}}/__admin/mappings

#### Requests
GET {{host}}/__admin/requests

#### Reset
POST {{host}}/__admin/reset

#### Shutdown
POST {{host}}/__admin/shutdown

#### Scenarios
GET {{host}}/__admin/scenarios
